### ISSUE TITLE
dual license?

### ISSUE THREAD

**Issue by msimerson** [Juul/tail-stream#3]
Would you consider dual licensing this under another license? Suggestions: BSD, MIT, [Artistic](https://www.npmjs.com/policies/npm-license), Apache, etc..

I have need of something just like tail-stream, and I've already written unit tests for it. I just can't use it for my intended purpose with a GPL license.

**Comment by Juul** [comment]
Maybe? What's your use case that doesn't allow Copyleft? If it's for integration with non-open code then I can offer you a commercial license. I'd usually charge for that but you already contributed so that sounds like a fair trade.

**Comment by msimerson** [comment]
I'm writing an "*I'm fed up with bugs in logstash-forwarder and logstash that result in millions of duplicate entries as well as millions of missing log entries in my Elasticsearch*" grudge application. Instead of just dumbly shipping logs to logstash, I'm going to read, read, parse, and normalize them locally, and then save directly to ES.  Most of the code is open (some is already on npm) and some is not.

To achieve this reliably, I need:

* something that reads log files and handles them growing, rotating, and appearing. tail-stream mostly handles that.
* persistent bookmarks, so that processed logs are remembered across program restarts
* flexible log file patterns (mail.log, mail.log.1.gz, mail.log.1.bz2, /var/log/http/2015/??/??/access.log)
* processing from log.gz files

and other fun things. After digging in further, I won't likely be using tail-stream as I've opted to write my own reader library that uses transform streams instead, so that I can:

```js
if (/\.gz$/.test(this.filePath)) {
    fs.createReadStream(this.filePath).pipe(zlib.createGunzip()).pipe(this.toLines);
    return;
}

fs.createReadStream(this.filePath, fileOpts).pipe(this.toLines);
```

**Comment by msimerson** [comment]
Oh, and writing my own avoids that whole "GPL" issue...
